// <auto-generated />
using System;
using CarStore.Clean.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarStore.Clean.Infrastructure.Migrations
{
    [DbContext(typeof(CarShopDBContext))]
    partial class CarShopDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarStore.Clean.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealerId")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("maker");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("price");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DealerId = 1,
                            Maker = "Toyota",
                            Model = "Camry",
                            Price = 22000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            DealerId = 2,
                            Maker = "Ford",
                            Model = "Focus",
                            Price = 18000m,
                            Year = 2019
                        });
                });

            modelBuilder.Entity("CarStore.Clean.Domain.Entities.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dealer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("contact_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dealers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactEmail = "contact@cityauto.com",
                            Name = "City Auto"
                        },
                        new
                        {
                            Id = 2,
                            ContactEmail = "sales@bestmotors.com",
                            Name = "Best Motors"
                        });
                });

            modelBuilder.Entity("CarStore.Clean.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_price");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sale_date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("sales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            FinalPrice = 21500m,
                            SaleDate = new DateTime(2025, 1, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            FinalPrice = 17500m,
                            SaleDate = new DateTime(2025, 2, 20, 15, 30, 0, 0, DateTimeKind.Utc),
                            UserId = "00000000-0000-0000-0000-000000000001"
                        });
                });

            modelBuilder.Entity("CarStore.Clean.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            Email = "john@example.com",
                            UserName = "johndoe"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            Email = "jane@example.com",
                            UserName = "janedoe"
                        });
                });

            modelBuilder.Entity("CarStore.Clean.Domain.Entities.Car", b =>
                {
                    b.HasOne("CarStore.Clean.Domain.Entities.Dealer", "Dealer")
                        .WithMany("Cars")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("CarStore.Clean.Domain.Entities.Sale", b =>
                {
                    b.HasOne("CarStore.Clean.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarStore.Clean.Domain.Entities.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarStore.Clean.Domain.Entities.Dealer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarStore.Clean.Domain.Entities.User", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
