services:
  api:
    container_name: carstore_clean_api
    build:
      context: .
      dockerfile: CarStore.Clean.WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=carstore_clean_db;Port=5432;Database=carstore_db;Username=postgres;Password=password;
    depends_on:
      carstore_clean_db:
        condition: service_healthy
    restart: on-failure

  carstore_clean_db:
    container_name: carstore_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carstore_db
    ports:
      - "5435:5432" 
    volumes:
      - carstore_clean:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  carstore_clean: